inherit_from: .rubocop_todo.yml
AllCops:
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - spec/factories/factories.rb

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: '#no-block-comments'
  Enabled: false
  VersionAdded: '0.9'
  VersionChanged: '0.23'

Style/Documentation:
  Description: 'Style/Documentation: Missing top-level documentation comment for class <name>'
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false